# Go parameters
GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) get

BINARY_SERVER_NAME=server
BINARY_SERVER_PATH=./cmd/$(BINARY_SERVER_NAME)

BINARY_CLIENT_NAME=client
BINARY_CLIENT_PATH=./cmd/$(BINARY_CLIENT_NAME)

BINARY_COBRA_NAME=zdora
BINARY_COBRA_PATH=./$(BINARY_COBRA_NAME)

BINARY_OUTPUT_PATH=./bin

build-linux:
	set CGO_ENABLED=0 GOOS=linux GOARCH=amd64
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_SERVER_NAME) -v $(BINARY_SERVER_PATH)
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_CLIENT_NAME) -v $(BINARY_CLIENT_PATH)
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_COBRA_NAME) -v $(BINARY_COBRA_PATH)

build-windows:
	set GOOS=windows
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_SERVER_NAME).exe -v $(BINARY_SERVER_PATH)
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_CLIENT_NAME).exe  -v $(BINARY_CLIENT_PATH)
	$(GOBUILD) -o $(BINARY_OUTPUT_PATH)/$(BINARY_COBRA_NAME).exe  -v $(BINARY_COBRA_PATH)

clean:
	$(GOCLEAN)
	rm -f $(BINARY_OUTPUT_PATH)/*

# Cross compilation
.PHONY: build
build:clean build-linux build-windows